# Generated by Django 4.1.1 on 2022-09-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('sonali', 'Sonali'), ('rupali', 'Rupali'), ('agrani', 'Agrani'), ('janata', 'Janata'), ('brac', 'BRAC'), ('ific', 'IFIC'), ('one', 'One'), ('dutch', 'Dutch')], default='sonali', max_length=6)),
            ],
        ),
    ]
