# Generated by Django 4.1.1 on 2022-09-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_System', '0002_taka'),
    ]

    operations = [
        migrations.AddField(
            model_name='taka',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
