# Generated by Django 4.1.1 on 2022-09-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_System', '0003_taka_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taka',
            old_name='payment_date',
            new_name='payment_time',
        ),
    ]
